src/TestMateManage/Models/Organization.cs
namespace TestMateManage.Models
{
    public class Organization
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
}

src/TestMateManage/ViewModels/Organization/OrganizationCreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TestMateManage.ViewModels
{
    public class OrganizationCreateViewModel
    {
        [Required]
        [StringLength(18, MinimumLength = 3)]
        public string Name { get; set; }

        [StringLength(500, MinimumLength = 10)]
        public string Description { get; set; }
    }
}

src/TestMateManage/ViewModels/Organization/OrganizationJoinViewModel.cs
using System.ComponentModel.DataAnnotations;
using TestMateManage.Models;

namespace TestMateManage.ViewModels
{
    public class OrganizationJoinViewModel
    {
        public RoleType Type { get; set; }

        [Range(0, int.MaxValue)]
        public int OrganizationId { get; set; }
    }
}

src/TestMateManage/ViewModels/Organization/OrganizationManagementRoleViewModel.cs
using System.Collections.Generic;

namespace TestMateManage.ViewModels
{
    public class OrganizationManagementRoleViewModel
    {
        public OrganizationRoleViewModel CurrentUser { get; set; }

        public IEnumerable<OrganizationRoleViewModel> Users { get; set; }

        public OrganizationNavigationViewModel Navigation { get; set; }
    }
}

src/TestMateManage/ViewModels/Organization/OrganizationNavigationViewModel.cs
namespace TestMateManage.ViewModels
{
    public class OrganizationNavigationViewModel
    {
        public int OrgId { get; set; }

        public bool IsTeacher { get; set; }
    }
}

src/TestMateManage/Controllers/AssignmentController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNet.Mvc;
using TestMateManage.Helpers;
using TestMateManage.Models;
using TestMateManage.ViewModels;
using Microsoft.Data.Entity;
using System.Configuration;

namespace TestMateManage.Controllers
{
    public class AssignmentController : BaseController
    {
        private readonly ITestMateDbContext _dbContext;
        private readonly ApiClient _testMateDevelopClient;
        private readonly ApiClient _testMateEvaluateClient;
        public AssignmentController(ITestMateDbContext dbContext)
        {
            _dbContext = dbContext;
            _testMateDevelopClient = new ApiClient("http://test-mate-develop.herokuapp.com/api/");
            _testMateEvaluateClient = new ApiClient("http://test-mate-evaluate.herokuapp.com/api/");
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var orgId = id;

            var userId = User.GetUserId();

            var templates = await _testMateDevelopClient.Get<IEnumerable<TemplateApiViewModel>>("templates/", new Dictionary<string, string>() {
                { "xauth", Security.ToBase64(userId) },
                { "xorgid", Security.ToBase64(orgId) }
            });

            var roles = _dbContext
                .OrganizationRoles
                .Include(x => x.User)
                .Include(x => x.Organization)
                .Where(x => x.OrganizationId == orgId && x.UserId != userId).ToList();

            var users = roles.OrderBy(x => x.Type).Select(x => new OrganizationRoleViewModel(x));

            var userRole = _dbContext.OrganizationRoles.Single(x => x.OrganizationId == id && x.UserId == userId);

            var model = new AssignmentCreateViewModel
            {
                Templates = templates,
                Users = users,
                Navigation = new OrganizationNavigationViewModel
                {
                    IsTeacher = userRole.Type == RoleType.Teacher,
                    OrgId = orgId
                }
            };

            return View(model);
        }


        [HttpPost, MembersOnly(Type = RoleType.Teacher)]
        public async Task<IActionResult> SaveAssignment(int id, [FromBody]AssignmentSaveViewModel data)
        {
            var dbRoles = _dbContext
                .OrganizationRoles
                .Include(x => x.User)
                .Include(x => x.Organization)
                .Where(x => x.OrganizationId == id && data.UserIds.Contains(x.UserId))
                .ToList();

            var roles = dbRoles.Select(x => new OrganizationRoleViewModel(x));

            foreach (var role in roles)
            {
                foreach (var template in data.Templates)
                {
                    var response = await _testMateEvaluateClient.Post<ApiResponse>("/api/assignment", new Dictionary<string, string>
                    {
                        { "assignee_id", Security.ToBase64(role.UserId) },
                        { "template_id", template.Id.ToString() },
                        { "template_title", template.Title },
                        { "organization_id", role.Id.ToString() },
                        { "organization_name", role.Name },
                        { "assigner_id", Security.ToBase64(User.GetUserId()) }
                    });

                }
            }

            return Ok();
        }

        [HttpGet, MembersOnly(Type = RoleType.Teacher)]
        public async Task<IActionResult> DoneAssignments(int id)
        {
            var url = string.Format("/api/done-evaluations/{0}", id);

            var response = await _testMateEvaluateClient.Get<IEnumerable<EvaluationApiResponse>>(url, new Dictionary<string, string>
            {
                { "xauth", Security.ToBase64(User.GetUserId()) }
            });

            var users =
                _dbContext.OrganizationRoles.Include(x => x.User).Where(x => x.OrganizationId == id).ToList();

            var assignments = response.Select(x => new DoneAssignmentViewModel(x)).ToList();

            foreach (var evaluation in assignments)
            {
                evaluation.Username = users.First(x => x.UserId == evaluation.UserId).User.UserName;
            }

            var userRole = _dbContext.OrganizationRoles.Single(x => x.OrganizationId == id && x.UserId == User.GetUserId());

            var model = new DoneAssignmentsViewModel
            {
                Assignments = assignments,
                Navigation = new OrganizationNavigationViewModel
                {
                    IsTeacher = userRole.Type == RoleType.Teacher,
                    OrgId = id
                }
            };

            return View(model);
        }

        [HttpGet, MembersOnly(Type = RoleType.Teacher)]
        public async Task<IActionResult> Check(int id, int evaluationId, string templateId)
        {
            var evaluationResultUrl = $"/api/assignment/result/{evaluationId}";

            var evaluationResult = await _testMateEvaluateClient.Get<Dictionary<string, IEnumerable<string>>>(evaluationResultUrl, new Dictionary<string, string>
            {
                { "xauth", Security.ToBase64(User.GetUserId()) }
            });

            var template = await _testMateDevelopClient.Get<TemplateFullApiViewModel>($"/api/templates/assignment-teacher/{templateId}", new Dictionary<string, string>
            {
                { "xauth", Security.ToBase64(User.GetUserId()) },
                { "xorgid", Security.ToBase64(id) },
            });

            var evaluation = AI.CheckEvaluation(template, evaluationResult);

            var userRole = _dbContext.OrganizationRoles.First(x => x.OrganizationId == id && x.UserId == User.GetUserId());

            var model = new AssignmentCheckViewModel
            {
                Evaluation = evaluation,
                Navigation = new OrganizationNavigationViewModel
                {
                    OrgId = id,
                    IsTeacher = userRole.Type == RoleType.Teacher
                },
                EvaluationId = evaluationId,
                AssignerId = userRole.UserId
            };

            return View(model);
        }

        [HttpPost, MembersOnly(Type = RoleType.Teacher)]
        public async Task<IActionResult> Save(int id, [FromBody]CheckedEvaluationApiModel input)
        {
            if (input == null)
            {
                return HttpBadRequest();
            }

            var evaluationResultUrl = $"/api/assignment/save-result/{input.EvaluationId}";

            var response = await _testMateEvaluateClient.Post<ApiResponse>(evaluationResultUrl, new Dictionary<string, string>
            {
                { "score", input.Score.ToString() }
            },
            new Dictionary<string, string>
            {
                { "xauth", Security.ToBase64(User.GetUserId()) }
            });

            if (response.Status == System.Net.HttpStatusCode.OK)
            {
                return Ok();
            }
            else
            {
                return HttpBadRequest(response);
            }
        }

        [HttpGet, MembersOnly(Type = RoleType.Teacher)]
        public async Task<IActionResult> History(int id, [FromQuery]string userId)
        {
            var evaluationResultUrl = $"/api/history/{id}/{userId}";

            var assignments = await _testMateEvaluateClient.Get<IEnumerable<AssignmentHistoryFullViewModel>>(evaluationResultUrl, new Dictionary<string, string>
            {
                { "xauth", Security.ToBase64(User.GetUserId()) }
            });

            var userRole = _dbContext.OrganizationRoles.First(x => x.OrganizationId == id && x.UserId == User.GetUserId());

            var model = new AssignmentHistoryViewModel
            {
                Assignments = assignments,
                Navigation = new OrganizationNavigationViewModel
                {
                    OrgId = id,
                    IsTeacher = userRole.Type == RoleType.Teacher
                }
            };

            return View(model);
        }

        [HttpGet, MembersOnly(Type = RoleType.Both)]
        public async Task<IActionResult> PersonalHistory(int id)
        {
            var evaluationResultUrl = $"/api/my-history/{id}";

            var assignments = await _testMateEvaluateClient.Get<IEnumerable<AssignmentHistoryFullViewModel>>(evaluationResultUrl, new Dictionary<string, string>
            {
                { "xauth", Security.ToBase64(User.GetUserId()) }
            });

            var userRole = _dbContext.OrganizationRoles.First(x => x.OrganizationId == id && x.UserId == User.GetUserId());

            var model = new AssignmentHistoryViewModel
            {
                Assignments = assignments,
                Navigation = new OrganizationNavigationViewModel
                {
                    OrgId = id,
                    IsTeacher = userRole.Type == RoleType.Teacher
                }
            };

            return View(model);
        }

    }
}

src/TestMateManage/Controllers/OrganizationController.cs
using System;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Newtonsoft.Json;
using TestMateManage.Helpers;
using TestMateManage.Models;
using TestMateManage.ViewModels;

namespace TestMateManage.Controllers
{
    public class OrganizationController : BaseController
    {
        private readonly ITestMateDbContext _dbContext;

        public OrganizationController(ITestMateDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public ActionResult Index()
        {
            var userId = User.GetUserId();

            var dbData = _dbContext
                .OrganizationRoles
                .Include(x => x.Organization)
                .Include(x => x.User)
                .Where(x => x.UserId == userId)
                .ToList();

            var model = dbData.Select(x => new OrganizationRoleViewModel(x)).ToList();

            return View(model);
        }

        public ActionResult Create(OrganizationCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var organization = new Organization()
                {
                    Description = model.Description,
                    Name = model.Name
                };

                _dbContext.Organizations.Add(organization);

                _dbContext.OrganizationRoles.Add(new OrganizationRole()
                {
                    Approved = true,
                    OrganizationId = organization.Id,
                    Type = RoleType.Teacher,
                    UserId = User.GetUserId()
                });

                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Test()
        {
            return Ok("secret");
        }

        public ActionResult List()
        {
            var userId = User.GetUserId();

            var userRoles = _dbContext
                .OrganizationRoles
                .Where(x => x.UserId == userId)
                .Select(y => y.OrganizationId).ToList();

            var organizations = _dbContext
                .Organizations
                .Where(org => userRoles.Contains(org.Id) == false)
                .ToList();

            var model = organizations.Select(org => new OrganizationViewModel(org)).ToList();

            return View(model);
        }

        public ActionResult Join(string data)
        {
            var inputRole = JsonConvert.DeserializeObject<OrganizationJoinViewModel>(data);

            var userId = User.GetUserId();

            var existingRole = _dbContext
                .OrganizationRoles
                .FirstOrDefault(x => x.OrganizationId == inputRole.OrganizationId && x.UserId == userId);

            if (existingRole != null)
            {
                throw new ArgumentException("Role already exists!");
            }

            var role = new OrganizationRole()
            {
                Approved = false,
                OrganizationId = inputRole.OrganizationId,
                UserId = userId,
                Type = inputRole.Type
            };


            _dbContext.OrganizationRoles.Add(role);

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Management(int id)
        {
            var userId = User.GetUserId();

            var role = _dbContext
                .OrganizationRoles
                .Include(x => x.Organization)
                .Include(x => x.User)
                .First(x => x.OrganizationId == id && x.UserId == userId);

            if (role == null || role.Approved == false)
            {
                return HttpBadRequest();
            }

            var roles = _dbContext
                .OrganizationRoles
                .Include(x => x.Organization)
                .Include(x => x.User)
                .OrderBy(x => x.Type)
                .ThenBy(x => x.User.UserName)
                .Where(x => x.OrganizationId == id && x.Id != role.Id && x.Approved == true).ToList();

            var model = new OrganizationManagementRoleViewModel
            {
                CurrentUser = new OrganizationRoleViewModel(role),
                Users = roles.Select(x => new OrganizationRoleViewModel(x)),
                Navigation = new OrganizationNavigationViewModel
                {
                    IsTeacher = role.Type == RoleType.Teacher,
                    OrgId = id 
                }
            };

            return View(model);
        }

        [HttpGet, MembersOnly(Type = RoleType.Teacher)]
        public IActionResult PendingMemberships(int id)
        {
            var orgId = id;

            var roles = _dbContext
                .OrganizationRoles
                .Include(x => x.Organization)
                .Include(x => x.User)
                .Where(x => x.OrganizationId == orgId && x.Approved == false).ToList();

            var memberships = roles.Select(x => new OrganizationRoleViewModel(x)).ToList();

            var userRole = _dbContext.OrganizationRoles.First(x => x.OrganizationId == orgId && x.UserId == User.GetUserId());

            var model = new OrganizationPendingMembershipsViewModel
            {
                Memberships = memberships,
                Navigation = new OrganizationNavigationViewModel
                {
                    IsTeacher = userRole.Type == RoleType.Teacher,
                    OrgId = orgId
                }
            };

            return View(model); 
        }

        [HttpPost, MembersOnly(Type = RoleType.Teacher)]
        public IActionResult ApproveMembership(int id, [FromBody]OrganizationRoleSimpleViewModel data)
        {
            var role = _dbContext.OrganizationRoles.FirstOrDefault(x => x.Id == data.RoleId);

            if (role == null)
            {
                return HttpNotFound();
            }

            if (role.OrganizationId != data.OrganizationId)
            {
                return HttpBadRequest();
            }

            role.Approved = true;

            _dbContext.SaveChanges();

            return Ok();
        }

        [HttpPost, MembersOnly(Type = RoleType.Teacher)]
        public IActionResult DenyMembership(int id, [FromBody]OrganizationRoleSimpleViewModel data)
        {
            var role = _dbContext.OrganizationRoles.FirstOrDefault(x => x.Id == data.RoleId);

            if (role == null)
            {
                return HttpNotFound();
            }

            if (role.OrganizationId != data.OrganizationId)
            {
                return HttpBadRequest();
            }

            _dbContext.OrganizationRoles.Remove(role);

            _dbContext.SaveChanges();

            return Ok();
        }
    }
}

src/TestMateManage/Views/Organization/Create.cshtml
@model OrganizationCreateViewModel

@section navigation {
    <li>
        <a asp-action="Create" class="navbar-brand">Create organization</a>
    </li>

    <li>
        <a asp-action="List" class="navbar-brand">View all organizations</a>
    </li>
}

<h2>Create new organization</h2>

@using (Html.BeginForm("Create", "Organization", FormMethod.Post))
{
    <div class="row">
        <div class="col-sm-12 form-group">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Organization name", pattern = ".{3,}", required="required", @title = "Title should be between 3 and 18 symbols." })


            @Html.TextAreaFor(x => x.Description, new { @class = "form-control", placeholder = "Organization description", pattern = ".{10,500}" })
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <button type="submit" class="btn btn-primary btn-block">Create</button>
        </div>
    </div>

    <pre>
        * Title should be between 3 and 18 symbols and is <strong>required</strong>.
        * Description should be between 10 and 500 symbols and is not required.
    </pre>
}

src/TestMateManage/Views/Organization/Index.cshtml
@model IList<OrganizationRoleViewModel>

@section navigation {
    <li>
        <a asp-action="Create" class="navbar-brand">Create organization</a>
    </li>

    <li>
        <a asp-action="List" class="navbar-brand">View all organizations</a>
    </li>
}

@if (Model.Count != 0)
{
    <h2>You're connected to several organizations:</h2>

    <table class="table table-stripped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Role</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>            
            @foreach (var role in Model)
            {
            <tr>
                <td>
                    @role.Name
                </td>
                <td>
                    @Html.Raw(GetRoleType(role))
                </td>
                <td>
                    @if (role.Approved == true)
                    {
                        <a asp-route-id="@role.Id" asp-action="management" class="btn btn-success btn-xs">Manage</a>
                    }
                    else
                    {
                        <a class="btn btn-success btn-xs disabled">Manage</a>
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>

    @if (Model.Any(x => x.Approved == false))
    {
    <pre class="alert">
* If you role is <button class='btn btn-warning btn-xs'>Pending</button> you should wait to be approved by teacher in organization. 
  Sometimes though you are not approved and if this happens the role will disappear.</pre>
    }
}
else
{
    <pre class="alert">
        At the current moment you are not connected to any organizations. You can check <a asp-action="List">"View all organizations"</a> section.
    </pre>
}

@functions {
        public string GetRoleType(OrganizationRoleViewModel role)
        {
            if (role.Approved == false)
            {
                return @"<button class='btn btn-warning btn-xs'>Pending</button>";
            }
            else if (role.Type == RoleType.Student)
            {
                return @"<button class='btn btn-info btn-xs'>Student</button>";

            }
            else
            {
                return @"<button class='btn btn-primary btn-xs'>Teacher</button>";
            }
        }
    }

src/TestMateManage/Views/Organization/List.cshtml
@model IList<OrganizationViewModel>

@section navigation {
    <li>
        <a asp-action="Create" class="navbar-brand">Create organization</a>
    </li>

    <li>
        <a asp-action="List" class="navbar-brand">View all organizations</a>
    </li>
}

@if (Model.Count == 0)
{
    <p>There are no organizations here, kid!</p>
}
else
{
    <table class="table table-stripped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var organization in Model)
            {
                <tr>
                    <td>@organization.Name</td>
                    <td>
                        <button 
                                class="btn btn-xs btn-primary join-organization" 
                                data-role="teacher"
                                data-organization-id="@organization.Id">Join as teacher</button>
                        <button class="btn btn-xs btn-info join-organization" 
                                data-role="student" 
                                data-organization-id="@organization.Id">Join as student</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

src/TestMateManage/Views/Organization/Management.cshtml
@model OrganizationManagementRoleViewModel

@section navigation {
    @Html.Partial("_OrganizationMenu", Model.Navigation)
}

<h4>Users in organization</h4>

@if (Model.Users.Any())
{
<table class="table table-stripped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Role</th>

            @if (Model.CurrentUser.Type == RoleType.Teacher)
            {
                <th>Options</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model.Users)
        {
            <tr>
                <td>@role.Username</td>
                <td>@role.Type</td>
                @if (Model.CurrentUser.Type == RoleType.Teacher)
                {
                    <td>
                        <a class="btn btn-info btn-xs" asp-action="History" asp-controller="Assignment" asp-route-id="@Model.Navigation.OrgId" asp-route-userId="@role.UserId">View results</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
}
else
{
    <pre class="alert alert-info">
        At the current moment there are not any approved users. You can check <a href="#">Approve</a> section. Or come back later.
    </pre>
}

src/TestMateManage/Views/Organization/PendingMemberships.cshtml
@model OrganizationPendingMembershipsViewModel

@section navigation {
    @Html.Partial("_OrganizationMenu", Model.Navigation)
}

@if (Model.Memberships.Count() == 0)
{
    <pre>
        At the current moment there are not any new members.
    </pre>
}
else
{
    <table class="table table-stripped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var membership in Model.Memberships)
            {
                <tr>
                    <td>@membership.Username</td>
                    <td>
                        @Html.Raw(GetRoleType(membership))
                    </td>
                    <td>
                        <button class="btn btn-xs btn-success approve-membership" data-org-id="@Model.Navigation.OrgId" data-role-id="@membership.RoleId">Approve</button>
                        <button class="btn btn-xs btn-danger deny-membership" data-org-id="@Model.Navigation.OrgId" data-role-id="@membership.RoleId">Deny</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@functions {
        public string GetRoleType(OrganizationRoleViewModel role)
        {
            if (role.Type == RoleType.Student)
            {
                return @"<button class='btn btn-info btn-xs'>Student</button>";

            }
            else
            {
                return @"<button class='btn btn-primary btn-xs'>Teacher</button>";
            }
        }
}